
### Get dashboard stats
GET http://localhost:3000/admin/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YjRiNTJlNC1iNDRkLTQxMmUtYWNjZi1kNGEzZGQ3MmIwNWYiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTIyNzQ3NCwiZXhwIjoxNzUxMzEzODc0fQ.9DQYMovXSBdrGk8S14msZOrR3luMdx_JFrkekheZ1a0


### Get all bookings
 GET http://localhost:3000/admin/bookings
 Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YjRiNTJlNC1iNDRkLTQxMmUtYWNjZi1kNGEzZGQ3MmIwNWYiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTIyNzQ3NCwiZXhwIjoxNzUxMzEzODc0fQ.9DQYMovXSBdrGk8S14msZOrR3luMdx_JFrkekheZ1a0


### Get all locations
GET http://localhost:3000/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YjRiNTJlNC1iNDRkLTQxMmUtYWNjZi1kNGEzZGQ3MmIwNWYiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTIyNzQ3NCwiZXhwIjoxNzUxMzEzODc0fQ.9DQYMovXSBdrGk8S14msZOrR3luMdx_JFrkekheZ1a0