
### Get dashboard stats
GET http://localhost:3000/admin/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzgzM2RhZC04YzI0LTQxYzYtYWUwYi1hZTRjNWYwYWQzYjgiLCJlbWFpbCI6ImRldnBldGVybmpvcm9nZUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEzNzI0ODEsImV4cCI6MTc1MTQ1ODg4MX0.nC9fUzLLQ-xiyaiAxZPr6hdrY-2kdBMbwK-CiP9SNfQ


### Get all bookings
 GET http://localhost:3000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzgzM2RhZC04YzI0LTQxYzYtYWUwYi1hZTRjNWYwYWQzYjgiLCJlbWFpbCI6ImRldnBldGVybmpvcm9nZUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEzNzI0ODEsImV4cCI6MTc1MTQ1ODg4MX0.nC9fUzLLQ-xiyaiAxZPr6hdrY-2kdBMbwK-CiP9SNfQ

### Get all locations
GET http://localhost:3000/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzgzM2RhZC04YzI0LTQxYzYtYWUwYi1hZTRjNWYwYWQzYjgiLCJlbWFpbCI6ImRldnBldGVybmpvcm9nZUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEzNzI0ODEsImV4cCI6MTc1MTQ1ODg4MX0.nC9fUzLLQ-xiyaiAxZPr6hdrY-2kdBMbwK-CiP9SNfQ


####
GET http://localhost:3000/bookings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzgzM2RhZC04YzI0LTQxYzYtYWUwYi1hZTRjNWYwYWQzYjgiLCJlbWFpbCI6ImRldnBldGVybmpvcm9nZUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEzNzI0ODEsImV4cCI6MTc1MTQ1ODg4MX0.nC9fUzLLQ-xiyaiAxZPr6hdrY-2kdBMbwK-CiP9SNfQ

###
PATCH http://localhost:3000/bookings/{bookingId}/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzgzM2RhZC04YzI0LTQxYzYtYWUwYi1hZTRjNWYwYWQzYjgiLCJlbWFpbCI6ImRldnBldGVybmpvcm9nZUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEzNzI0ODEsImV4cCI6MTc1MTQ1ODg4MX0.nC9fUzLLQ-xiyaiAxZPr6hdrY-2kdBMbwK-CiP9SNfQ

###
PATCH http://localhost:3000/bookings/{bookingId}/reject
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2YzgzM2RhZC04YzI0LTQxYzYtYWUwYi1hZTRjNWYwYWQzYjgiLCJlbWFpbCI6ImRldnBldGVybmpvcm9nZUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTEzNzI0ODEsImV4cCI6MTc1MTQ1ODg4MX0.nC9fUzLLQ-xiyaiAxZPr6hdrY-2kdBMbwK-CiP9SNfQ
Content-Type: application/json

{
  "reason": "Optional reason for rejection"
}