

### 1. Register admin
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Peter Njoroge",
  "email": "devpeternjoroge@gmail.com",
  "password": "Admin123!",
  "role": "ADMIN"
}

### 2. Login and get token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "devpeternjoroge@gmail.com",
  "password": "Admin123!"
}

### 3. Test protected endpoint (replace TOKEN with actual token from login)
GET http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YjRiNTJlNC1iNDRkLTQxMmUtYWNjZi1kNGEzZGQ3MmIwNWYiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTIyNTM3OCwiZXhwIjoxNzUxMzExNzc4fQ.IhwfDcAZ97IdZiNxyQE2cnKwFCvZdqSVOWURXG0JvK4
Content-Type: application/json

### 4. Update profile - Add phone number
PATCH http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQxN2RjYi01ZWZmLTRiMjEtYjBlMS02ZGZmYjM0NWFhZDMiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTE3NTAxMiwiZXhwIjoxNzUxMjYxNDEyfQ.J4h0cI2PfhZrPz-IWimVM9xFq0wKYojRFbWf9ff3BH0
Content-Type: application/json

{
  "phone": "+254712345678",
  "profileImage": "https://example.com/profile.jpg"
}

### 5. Update profile - Change name
PATCH http://localhost:3000/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3YjRiNTJlNC1iNDRkLTQxMmUtYWNjZi1kNGEzZGQ3MmIwNWYiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTIyNTM3OCwiZXhwIjoxNzUxMzExNzc4fQ.IhwfDcAZ97IdZiNxyQE2cnKwFCvZdqSVOWURXG0JvK4
Content-Type: application/json

{
  "name": "Peter Njuguna Updated"
}

### 6. Register a new customer (Public)
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "John Customer",
  "email": "alexmucheke511@gmail.com",
  "password": "CustomerPass123!",
  "role": "CUSTOMER"
}

### 7. Admin creates customer (Protected - Admin Only)
POST http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQxN2RjYi01ZWZmLTRiMjEtYjBlMS02ZGZmYjM0NWFhZDMiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTE3NTAxMiwiZXhwIjoxNzUxMjYxNDEyfQ.J4h0cI2PfhZrPz-IWimVM9xFq0wKYojRFbWf9ff3BH0
Content-Type: application/json

{
  "name": "Alex Customer",
  "email": "peterjuniordev27@gmail.com",
  "password": "CustomerPass123!",
  "role": "CUSTOMER"
}

### 8 get alll users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQxN2RjYi01ZWZmLTRiMjEtYjBlMS02ZGZmYjM0NWFhZDMiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTE3NTAxMiwiZXhwIjoxNzUxMjYxNDEyfQ.J4h0cI2PfhZrPz-IWimVM9xFq0wKYojRFbWf9ff3BH0

### 9 get one user
GET http://localhost:3000/users/35ada519-d3b3-46a8-b12d-69c272d6c10c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQxN2RjYi01ZWZmLTRiMjEtYjBlMS02ZGZmYjM0NWFhZDMiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTE3NTAxMiwiZXhwIjoxNzUxMjYxNDEyfQ.J4h0cI2PfhZrPz-IWimVM9xFq0wKYojRFbWf9ff3BH0

### delete user
DELETE http://localhost:3000/users/35ada519-d3b3-46a8-b12d-69c272d6c10c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQxN2RjYi01ZWZmLTRiMjEtYjBlMS02ZGZmYjM0NWFhZDMiLCJlbWFpbCI6Im5qdWd1bmFocGV0ZXJuam9yb2dlQGdtYWlsLmNvbSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc1MTE3NTAxMiwiZXhwIjoxNzUxMjYxNDEyfQ.J4h0cI2PfhZrPz-IWimVM9xFq0wKYojRFbWf9ff3BH0